version: '3'

services:
  mongo_db:
    image: mongo:6.0.2
    ports:
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongod --port 27019

  backend:
    build: .
    command: uvicorn app:app --host 0.0.0.0
    ports:
      - 8000:8000
    depends_on:
      - mongo_db
    environment:
      MONGO_CONN_STR: mongodb://root:root@mongo_db:27019/?authMechanism=DEFAULT

networks:
  default:
    name: travelator_net